### ISSUE TITLE
How to access a graph in Cosmos DB with SQL / DocumentDB API through java spring boot application?

### ISSUE THREAD

**Issue by shivani-sachdeva** [vplauzon/cosmos-db#1]
I came across your [article](https://vincentlauzon.com/2017/09/05/hacking-accessing-a-graph-in-cosmos-db-with-sql-documentdb-api/) on accessing a graph in Cosmos DB with SQL / DocumentDB API from .net app.

I have an exact similar use case to implement but from java application.
Could you share any leads there?

**Comment by vplauzon** [comment]
Hi Shivani,


I've never used the Java SDK with Cosmos DB.  I would probably have a look at [this article](https://docs.microsoft.com/en-us/azure/cosmos-db/create-graph-java) to get started.

VP
